### ISSUE TITLE
Competencias Genéricas

### ISSUE THREAD

**Issue by Killercrod** [Killercrod/Equipo-1-FIS-Repositorio#47]

**Comment by IvanChiPolanco** [comment]
Escribí las competencias de las materias de tercer semestre.

**Comment by BraulioTelloMancilla** [comment]
Escribí las competencias genéricas y disciplinares de las materias obligatorias de primer semestre

**Comment by KERMITH79** [comment]
Escribir las competencias de cada materia de segundo semestre
