### ISSUE TITLE
Competencias Especificas

### ISSUE THREAD

**Issue by Killercrod** [Killercrod/Equipo-1-FIS-Repositorio#48]

**Comment by IvanChiPolanco** [comment]
Escribí las competencias específicas de las materias de tercer semestre

**Comment by jsrangel666** [comment]
Yo realice las competencias específicas de las materias : Responsabilidad Social Universitaria (RSU), Álgebra Intermedia, Algoritmia, Geometría Analítica, Fundamentos de Ingeniería de Software.

**Comment by KERMITH79** [comment]
Realice las competencias específicas de segundo semestre

**Comment by JonEsp87** [comment]
Competencias específicas del tercer semestre.
