### ISSUE TITLE
Historias de usuario

### ISSUE THREAD

**Issue by Killercrod** [Killercrod/Equipo-1-FIS-Repositorio#59]

**Comment by IvanChiPolanco** [comment]
Escribí los reqs para los siguientes requerimientos:
.La guía le enseña al usuario por medio de colores las materias en las que tiene una mayor o menor posibilidad de pasar esa materia.
.La guía da consejos en el caso que el usuario desee elegir una materia de la cual la evaluación le ha declarado que aún no esta preparado.
.La guía da consejos en el caso que el usuario elija una materia que si tenga oportunidad de pasar pero se le dificulte.
